import { z } from "zod";

/**
 * The tenant-selectable theme presets. Each id MUST have a matching
 * `[data-theme="<id>"]` block in `app/themes.css` (generated by
 * `scripts/gen-themes.mjs`). Single source of truth for the settings schema
 * and the admin picker.
 *
 * `swatch` is only for the picker UI — three representative colours per mode so
 * the grid can preview a theme without applying it.
 */
export type ThemePresetId =
  | "modern-minimal"
  | "clean-slate"
  | "supabase"
  | "ocean-breeze"
  | "nature"
  | "claude"
  | "vintage-paper"
  | "amber-minimal"
  | "midnight-bloom"
  | "neo-brutalism";

export type ThemePreset = {
  id: ThemePresetId;
  label: string;
  description: string;
  swatch: { light: [string, string, string]; dark: [string, string, string] };
};

export const THEME_PRESETS: readonly ThemePreset[] = [
  {
    id: "modern-minimal",
    label: "Modern Minimal",
    description: "Clean blue on white. Safe default for most organizations.",
    swatch: {
      light: ["oklch(1 0 0)", "oklch(0.6231 0.188 259.8145)", "oklch(0.967 0.0029 264.5419)"],
      dark: ["oklch(0.2046 0 0)", "oklch(0.6231 0.188 259.8145)", "oklch(0.2686 0 0)"],
    },
  },
  {
    id: "clean-slate",
    label: "Clean Slate",
    description: "Neutral slate with a violet accent. Understated and corporate.",
    swatch: {
      light: ["oklch(0.9842 0.0034 247.8575)", "oklch(0.5854 0.2041 277.1173)", "oklch(0.9276 0.0058 264.5313)"],
      dark: ["oklch(0.2077 0.0398 265.7549)", "oklch(0.6801 0.1583 276.9349)", "oklch(0.2795 0.0368 260.031)"],
    },
  },
  {
    id: "supabase",
    label: "Supabase",
    description: "Bright green on near-white. Technical and energetic.",
    swatch: {
      light: ["oklch(0.9911 0 0)", "oklch(0.8348 0.1302 160.908)", "oklch(0.9461 0 0)"],
      dark: ["oklch(0.1822 0 0)", "oklch(0.4365 0.1044 156.7556)", "oklch(0.2603 0 0)"],
    },
  },
  {
    id: "ocean-breeze",
    label: "Ocean Breeze",
    description: "Cool teal and soft blues. Calm, spacious feel.",
    swatch: {
      light: ["oklch(0.9842 0.0034 247.8575)", "oklch(0.7227 0.192 149.5793)", "oklch(0.9288 0.0126 255.5078)"],
      dark: ["oklch(0.2077 0.0398 265.7549)", "oklch(0.7227 0.192 149.5793)", "oklch(0.2795 0.0368 260.031)"],
    },
  },
  {
    id: "nature",
    label: "Nature",
    description: "Deep forest greens on warm cream. Grounded and organic.",
    swatch: {
      light: ["oklch(0.9711 0.0074 80.7211)", "oklch(0.5234 0.1347 144.1672)", "oklch(0.9370 0.0142 74.4218)"],
      dark: ["oklch(0.2683 0.0279 150.7681)", "oklch(0.6731 0.1624 144.2083)", "oklch(0.3327 0.0271 146.9867)"],
    },
  },
  {
    id: "claude",
    label: "Claude",
    description: "Warm terracotta on parchment. Editorial and human.",
    swatch: {
      light: ["oklch(0.9818 0.0054 95.0986)", "oklch(0.6171 0.1375 39.0427)", "oklch(0.9245 0.0138 92.9892)"],
      dark: ["oklch(0.2679 0.0036 106.6427)", "oklch(0.6724 0.1308 38.7559)", "oklch(0.3078 0.0066 106.5230)"],
    },
  },
  {
    id: "vintage-paper",
    label: "Vintage Paper",
    description: "Sepia and aged card stock. Bookish, low-glare.",
    swatch: {
      light: ["oklch(0.9582 0.0152 90.2357)", "oklch(0.6180 0.0778 65.5444)", "oklch(0.9239 0.0190 83.0636)"],
      dark: ["oklch(0.2679 0.0036 106.6427)", "oklch(0.7264 0.0581 66.6967)", "oklch(0.3225 0.0075 106.5230)"],
    },
  },
  {
    id: "amber-minimal",
    label: "Amber Minimal",
    description: "Amber on clean white. High energy, high contrast.",
    swatch: {
      light: ["oklch(1 0 0)", "oklch(0.7686 0.1647 70.0804)", "oklch(0.9670 0.0029 264.5419)"],
      dark: ["oklch(0.2046 0 0)", "oklch(0.7686 0.1647 70.0804)", "oklch(0.2686 0 0)"],
    },
  },
  {
    id: "midnight-bloom",
    label: "Midnight Bloom",
    description: "Deep indigo and violet. Dramatic, works best in dark mode.",
    swatch: {
      light: ["oklch(0.9842 0.0034 247.8575)", "oklch(0.5676 0.2021 283.0838)", "oklch(0.9288 0.0126 255.5078)"],
      dark: ["oklch(0.2077 0.0398 265.7549)", "oklch(0.6132 0.2294 291.7437)", "oklch(0.2795 0.0368 260.0310)"],
    },
  },
  {
    id: "neo-brutalism",
    label: "Neo Brutalism",
    description: "Hard black outlines, saturated red, zero-blur shadows.",
    swatch: {
      light: ["oklch(1 0 0)", "oklch(0.6489 0.2370 26.9728)", "oklch(0.9691 0.0161 293.7562)"],
      dark: ["oklch(0 0 0)", "oklch(0.7044 0.1872 23.1858)", "oklch(0.3211 0 0)"],
    },
  },
] as const;

export const DEFAULT_THEME_PRESET: ThemePresetId = "modern-minimal";

const IDS = THEME_PRESETS.map((p) => p.id) as [ThemePresetId, ...ThemePresetId[]];

export const themePresetSchema = z.enum(IDS);

export function isThemePresetId(value: unknown): value is ThemePresetId {
  return typeof value === "string" && IDS.includes(value as ThemePresetId);
}

export function getThemePreset(id: ThemePresetId): ThemePreset {
  return THEME_PRESETS.find((p) => p.id === id) ?? THEME_PRESETS[0];
}
