// Generates app/themes.css from the tweakcn shadcn registry.
// Run: node gen-themes.mjs > app/themes.css
import { writeFileSync } from "node:fs";

const PRESETS = [
  ["modern-minimal", "Modern Minimal"],
  ["clean-slate", "Clean Slate"],
  ["supabase", "Supabase"],
  ["ocean-breeze", "Ocean Breeze"],
  ["nature", "Nature"],
  ["claude", "Claude"],
  ["vintage-paper", "Vintage Paper"],
  ["amber-minimal", "Amber Minimal"],
  ["midnight-bloom", "Midnight Bloom"],
  ["neo-brutalism", "Neo Brutalism"],
];

// Typography is owned by the app (next/font), never by a preset.
const DROP = new Set([
  "font-sans",
  "font-serif",
  "font-mono",
  "tracking-normal",
  "spacing",
  "letter-spacing",
]);

// --- colour maths (sRGB hex / oklch string -> OKLCh components) -------------
function srgbToLinear(c) {
  return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
}
function hexToOklch(hex) {
  const h = hex.replace("#", "");
  const full =
    h.length === 3
      ? h
          .split("")
          .map((c) => c + c)
          .join("")
      : h;
  const r = srgbToLinear(parseInt(full.slice(0, 2), 16) / 255);
  const g = srgbToLinear(parseInt(full.slice(2, 4), 16) / 255);
  const b = srgbToLinear(parseInt(full.slice(4, 6), 16) / 255);
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  const L = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s;
  const A = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
  const B = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;
  return { L, C: Math.hypot(A, B) };
}
/** Best-effort parse of whatever colour syntax a preset used. */
function parseLC(value) {
  if (!value) return null;
  const v = value.trim();
  let m = v.match(/oklch\(\s*([\d.]+%?)\s+([\d.]+)\s+([\d.]+)/i);
  if (m) {
    const L = m[1].endsWith("%") ? parseFloat(m[1]) / 100 : parseFloat(m[1]);
    return { L, C: parseFloat(m[2]) };
  }
  m = v.match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i);
  if (m) return hexToOklch(v);
  return null;
}

// Status hues. Fixed hue keeps meaning stable ("overdue is always red-ish");
// L and C are borrowed from the preset so they sit inside its palette.
const STATUS_HUES = { success: 150, warning: 75, info: 245 };

function deriveStatus(vars, isDark) {
  const ref = parseLC(vars["primary"]) ?? { L: isDark ? 0.75 : 0.62, C: 0.15 };
  // Clamp into a band that stays legible against the preset's background.
  const L = Math.min(0.86, Math.max(isDark ? 0.68 : 0.55, ref.L));
  // Low-chroma (greyscale/mono) presets get muted status colours so they don't
  // scream against an otherwise desaturated palette.
  const C = Math.min(0.17, Math.max(0.05, ref.C < 0.03 ? 0.06 : ref.C));
  const out = {};
  for (const [name, hue] of Object.entries(STATUS_HUES)) {
    const l = name === "warning" ? Math.min(0.88, L + 0.06) : L;
    out[name] = `oklch(${l.toFixed(4)} ${C.toFixed(4)} ${hue.toFixed(4)})`;
    // Contrast pair computed from lightness, so it can never desync.
    out[`${name}-foreground`] =
      l >= 0.62 ? "oklch(0.1450 0 0)" : "oklch(0.9850 0 0)";
  }
  return out;
}

function block(selector, vars, isDark) {
  const lines = [];
  for (const [k, v] of Object.entries(vars)) {
    if (DROP.has(k)) continue;
    lines.push(`  --${k}: ${v};`);
  }
  for (const [k, v] of Object.entries(deriveStatus(vars, isDark))) {
    lines.push(`  --${k}: ${v};`);
  }
  return `${selector} {\n${lines.join("\n")}\n}`;
}

const out = [
  "/* GENERATED by scripts/gen-themes.mjs — do not edit by hand.",
  " * Source: https://tweakcn.com/r/themes/{slug}.json",
  " *",
  " * Selectors are [data-theme=\"x\"]:not(.dark) / [data-theme=\"x\"].dark (0,2,0)",
  " * so they beat the (0,1,0) :root and .dark blocks in globals.css regardless",
  " * of import order. A plain [data-theme=\"x\"] would tie with .dark and let a",
  " * light preset win in dark mode.",
  " *",
  " * Font vars are stripped deliberately: typography comes from next/font in",
  " * app/layout.tsx. Status tokens (success/warning/info) are derived per preset",
  " * because tweakcn does not ship them.",
  " */",
  "",
];

for (const [slug, label] of PRESETS) {
  const res = await fetch(`https://tweakcn.com/r/themes/${slug}.json`);
  if (!res.ok) {
    console.error(`FAILED ${slug}: ${res.status}`);
    continue;
  }
  const json = await res.json();
  const cv = json.cssVars ?? {};
  const shared = cv.theme ?? {};
  const light = { ...shared, ...(cv.light ?? {}) };
  const dark = { ...shared, ...(cv.dark ?? {}) };
  out.push(`/* ── ${label} ─────────────────────────────────────────── */`);
  out.push(block(`[data-theme="${slug}"]:not(.dark)`, light, false));
  out.push(block(`[data-theme="${slug}"].dark`, dark, true));
  out.push("");
  console.error(`ok ${slug} (${Object.keys(light).length} light vars)`);
}

writeFileSync(process.argv[2], out.join("\n"), "utf8");
console.error(`\nwrote ${process.argv[2]}`);
